import test from 'node:test'
import assert from 'node:assert/strict'
import { mapPoint, expeditionObjective } from './navigation.js'
import { createExpedition, stepExpedition, interact, WORLD } from './expedition.js'
test('north-up map bounds invalid and off-world coordinates without changing game state', () => { assert.deepEqual(mapPoint({ x: 0, z: 0 }), { x: 50, y: 50 }); assert.deepEqual(mapPoint({ x: -17, z: 17 }), { x: 0, y: 100 }); assert.deepEqual(mapPoint({ x: Infinity, z: -999 }), { x: 50, y: 0 }) })
test('objective uses uncollected supplies then repair then exit without autoplay', () => { const state = createExpedition(); const before = structuredClone(state); assert.equal(expeditionObjective(state).id, 0); assert.deepEqual(state, before); state.player.x = -10; interact(state); assert.notEqual(expeditionObjective(state).id, 0); state.player.scrap = 4; assert.equal(expeditionObjective(state).kind, 'cell'); state.player.cells = 2; assert.equal(expeditionObjective(state).kind, 'repair'); state.repaired = true; assert.equal(expeditionObjective(state).kind, 'exit'); assert.ok(expeditionObjective(state).distance > 0) })
test('missing supply returns no false destination', () => { const state = createExpedition(); state.loot = []; assert.equal(expeditionObjective(state), null) })
test('practice mode has a longer window and slower patrols, with same mission requirements', () => { const practice = createExpedition('same', { difficulty: 'practice' }), normal = createExpedition('same'); assert.equal(practice.limitSeconds, 300); assert.equal(normal.limitSeconds, 180); assert.deepEqual(practice.loot, normal.loot); Object.assign(practice.player, WORLD.beacon); assert.equal(interact(practice), false); practice.elapsed = 180; practice.enemies = []; stepExpedition(practice); assert.equal(practice.status, 'playing'); practice.elapsed = 299.99; stepExpedition(practice); assert.equal(practice.status, 'lost'); assert.throws(() => createExpedition('same', { difficulty: 'impossible' })) })
test('practice damage is milder without removing patrol threat', () => { const state = createExpedition('test', { difficulty: 'practice' }); state.player.invulnerable = 0; state.enemies = [{ ...state.player, homeX: state.player.x, homeZ: state.player.z, phase: 0 }]; stepExpedition(state); assert.equal(state.player.health, 92) })
