import test from 'node:test'
import assert from 'node:assert/strict'
import { BUILDINGS,CAMP_ROCKS,createSettlement,placement,buildCamp,campInteract,allocatePower,stepSettlement,upgradeCamp,campRoute,startNight } from './settlement.js'
test('seeded camps are repeatable and five building types have real resource gates',()=>{assert.deepEqual(createSettlement('abc'),createSettlement('abc'));assert.equal(BUILDINGS.length,5);assert.throws(()=>createSettlement('','normal'));const s=createSettlement();assert.ok(placement(s,'garden',4,0).ok);const bank=s.resources.wood;assert.ok(buildCamp(s,'garden',4,0));assert.equal(s.resources.wood,bank-3);assert.ok(!buildCamp(s,'garden',4,0));assert.ok(!buildCamp(s,'wall',0,0));s.resources.scrap=0;assert.ok(!buildCamp(s,'turret',6,0))})
test('movement handles invalid input, diagonal normalization, collision and dash cooldown',()=>{const a=createSettlement(),b=createSettlement();a.player.x=b.player.x=4;a.player.z=b.player.z=6;stepSettlement(a,{x:1},.05);stepSettlement(b,{x:1,z:1},.05);assert.ok(Math.abs(Math.hypot(b.player.x-4,b.player.z-6)-(a.player.x-4))<1e-8);stepSettlement(a,{x:NaN,z:Infinity},Infinity);assert.ok(Number.isFinite(a.player.x));assert.equal(a.elapsed,.05);stepSettlement(a,{x:1,dash:true},.05);const dash=a.player.dashCooldown;stepSettlement(a,{x:1,dash:true},.05);assert.ok(a.player.dashCooldown<dash);const c=createSettlement();c.player.x=2;c.player.z=0;for(let i=0;i<100;i++)stepSettlement(c,{x:-1},.05);assert.ok(c.player.x>1.1)})
test('harvest needs proximity, decreases remaining nodes and repair consumes resources only if useful',()=>{const s=createSettlement();assert.equal(campInteract(s),false);s.player.x=-4;s.player.z=4;const before=s.resources.wood;assert.ok(campInteract(s));assert.equal(s.resources.wood,before+3);assert.equal(s.nodes[0].remaining,2);s.player.x=2;s.player.z=0;s.base.hp=100;assert.ok(campInteract(s));assert.equal(s.base.hp,140);assert.equal(s.resources.wood,before+2)})
test('powered turrets allocate scarce supply and generator destruction revokes power',()=>{const s=createSettlement();buildCamp(s,'turret',4,0);assert.equal(s.buildings.filter(b=>b.powered).length,1);assert.ok(buildCamp(s,'generator',4,-2));assert.equal(s.buildings.filter(b=>b.powered).length,2);s.buildings=s.buildings.filter(b=>b.kind!=='generator');allocatePower(s);assert.equal(s.buildings.filter(b=>b.powered).length,1)})
test('real waves can damage camp and fire reduces enemies with finite bounds',()=>{const s=createSettlement();s.cycle=34;stepSettlement(s,{},.05);assert.equal(s.enemies.length,1);assert.equal(s.night,true);s.enemies[0].x=2;s.enemies[0].z=4;const hp=s.enemies[0].hp;stepSettlement(s,{fire:true},.05);assert.ok(s.enemies[0]?.hp<hp||!s.enemies.length);s.enemies=[{id:100,x:0,z:1.4,type:'scout',hp:30,maxHp:30,cooldown:0}];stepSettlement(s,{},.05);assert.ok(s.base.hp<180)})
test('day completion grows resources, charges provisions, freezes upgrade choice and caps final run',()=>{const s=createSettlement();buildCamp(s,'garden',4,0);buildCamp(s,'water',4,-2);s.cycle=60;s.spawned=6;stepSettlement(s,{},.05);assert.equal(s.day,2);assert.equal(s.resources.food,6);assert.equal(s.resources.water,7);assert.ok(s.awaitUpgrade);const now=s.elapsed;stepSettlement(s,{x:1},.05);assert.equal(s.elapsed,now);assert.ok(!upgradeCamp(s,'forged'));assert.ok(upgradeCamp(s,'supply'));assert.equal(s.resources.scrap,21);s.cycle=60;s.spawned=8;stepSettlement(s,{},.05);assert.equal(s.day,3);upgradeCamp(s,'reinforce');s.cycle=60;s.spawned=10;stepSettlement(s,{},.05);assert.equal(s.status,'won');const end=s.elapsed;stepSettlement(s,{},.05);assert.equal(s.elapsed,end)})
test('starvation and player loss have real consequences without negative resource balances',()=>{const s=createSettlement();s.resources.food=0;s.resources.water=0;s.base.hp=40;s.cycle=60;s.spawned=6;stepSettlement(s,{},.05);assert.equal(s.status,'lost');assert.ok(s.resources.food>=0);const b=createSettlement();b.player.hp=0;stepSettlement(b,{},.05);assert.equal(b.status,'lost')})
test('grid routes avoid fixed ruins and a real three-night strategy wins without state injection',()=>{const route=campRoute({x:-13,z:-10},{x:0,z:0});assert.ok(route.length>15);assert.ok(route.every(p=>!CAMP_ROCKS.some(r=>Math.abs(p.x-r.x)<1.65&&Math.abs(p.z-r.z)<1.65)));const s=createSettlement();for(const [type,x,z] of [['garden',4,4],['water',2,6],['generator',0,4],['turret',2,8]])assert.ok(buildCamp(s,type,x,z));let ticks=0;startNight(s);while(s.status==='playing'&&ticks++<12000){if(s.awaitUpgrade){upgradeCamp(s,'reinforce');startNight(s)}stepSettlement(s,{fire:true},.05)}assert.equal(s.status,'won');assert.equal(s.kills,24);assert.ok(s.elapsed<130)})
