import test from 'node:test'
import assert from 'node:assert/strict'
import { createHash, createCipheriv } from 'node:crypto'
import { caesar,vigenere,xorTrace,sha256Trace,aes128Trace,rsaTrace,dhTrace,parseHex } from './algorithms.js'
test('classical ciphers preserve nonletters and round-trip with explicit reverse',()=>{ assert.equal(caesar('Hello, 世界!',3).result,'Khoor, 世界!'); assert.equal(caesar('Khoor',3,true).result,'Hello'); const v = vigenere('ATTACK AT DAWN','LEMON').result; assert.equal(v,'LXFOPV EF RNHR'); assert.equal(vigenere(v,'LEMON',true).result,'ATTACK AT DAWN') })
test('XOR operates on UTF-8 bytes and shows bit-level evidence',()=>{ assert.equal(xorTrace('A','B').result,'03'); assert.equal(xorTrace('中','x').steps.length,3); assert.throws(()=>xorTrace('x','')) })
test('SHA256 agrees with Node on empty, Unicode, padding boundaries and multiblock',()=>{ for(const text of ['', 'abc','中文🙂','a'.repeat(55),'a'.repeat(56),'a'.repeat(64),'a'.repeat(256)]) assert.equal(sha256Trace(text).result,createHash('sha256').update(text).digest('hex')); assert.equal(sha256Trace('abc').steps.filter(s=>s.title.includes('压缩轮')).length,64) })
test('AES128 matches NIST known vector and randomized independent ECB oracle',()=>{ assert.equal(aes128Trace('00112233445566778899aabbccddeeff','000102030405060708090a0b0c0d0e0f').result,'69c4e0d86a7b0430d8cdb78070b4c55a'); for(let i=0;i<15;i++){const k = Buffer.alloc(16,i), input=Buffer.from(Array.from({length:16},(_,j)=>(i*31+j*17)%256)), cipher=createCipheriv('aes-128-ecb',k,null);cipher.setAutoPadding(false); assert.equal(aes128Trace(input.toString('hex'),k.toString('hex')).result,Buffer.concat([cipher.update(input),cipher.final()]).toString('hex'))} const steps=aes128Trace('00'.repeat(16),'00'.repeat(16)).steps;assert.equal(steps.filter(s=>s.title.includes('MixColumns')).length,9);assert.equal(steps.filter(s=>s.title.includes('AddRoundKey')).length,11);assert.ok(steps.every(s=>s.values.length===16)) })
test('RSA exponent trace recovers all small messages and rejects invalid primes/exponents',()=>{ assert.match(rsaTrace(61,53,17,65).result,/密文 2790；恢复 65/);for(let m=0;m<55;m++)assert.match(rsaTrace(5,11,3,m).result,new RegExp(`恢复 ${m}；`));assert.throws(()=>rsaTrace(9,53,17,65));assert.throws(()=>rsaTrace(61,53,6,65)) })
test('DH produces equal shared secret and validates public integer bounds',()=>{assert.equal(dhTrace(23,5,6,15).result,'Alice = 2；Bob = 2');assert.throws(()=>dhTrace(21,5,6,15));assert.throws(()=>dhTrace(23,1,6,15))})
test('resource bounds and exact AES input validation fail closed',()=>{assert.throws(()=>sha256Trace('中'.repeat(100)));assert.throws(()=>parseHex('a',16));assert.throws(()=>caesar('abc',NaN));assert.throws(()=>vigenere('abc','中文'));assert.throws(()=>rsaTrace('',53,17,65))})
