export const ALGORITHMS = [
  { id:'aes', name:'AES-128', kind:'对称分组密码', hint:'16 字节明文与 16 字节密钥，均填写 32 位 HEX。演示单块加密，无模式、填充或认证。', principle:'先将字节放入状态矩阵，再经过密钥异或、非线性替换、行移位与列混合。10 轮中，最后一轮没有列混合。矩阵按行展示，输入按列填入。', flow:['输入 4×4 状态','SubBytes 字节替换','ShiftRows 行移位','MixColumns 列混合','AddRoundKey 密钥异或'], warning:'这是内部轮函数实验，不是安全文件加密工具；不要输入真实密钥。', source:'https://csrc.nist.gov/pubs/fips/197/final', sourceTitle:'NIST FIPS 197' },
  { id:'sha', name:'SHA-256', kind:'密码散列', hint:'输入最多 256 个 UTF-8 字节，可包含中文。', principle:'编码并填充为 512 位消息块，每块扩展 64 个字，执行 64 轮压缩，把八个 32 位链值累加，最后得到 256 位摘要。每轮使用真实输入及常数，不是预录动画。', flow:['UTF-8 与长度填充','扩展 64 个消息字','64 轮压缩寄存器','链值累加与摘要'], warning:'散列不可逆，不是加密；裸 SHA-256 也不是适合直接存储密码的方案。', source:'https://csrc.nist.gov/pubs/fips/180-4/upd1/final', sourceTitle:'NIST FIPS 180-4' },
  { id:'rsa', name:'RSA 小整数', kind:'非对称密码教学', hint:'p、q 为不同素数 3–997；e 与 φ(n) 互素；输入整数 0 ≤ m < n。', principle:'素数相乘形成 n，通过扩展欧几里得求私钥指数 d。加密、解密使用平方乘模幂，逐个指数位记录底数与累积值。', flow:['素数与公钥参数','求模逆得到 d','平方乘模幂','解密恢复整数'], warning:'小密钥、裸 RSA 无填充，仅解释代数。真实加密需要合适密钥长度、OAEP 等方案；不用于保护秘密。', source:'https://www.rfc-editor.org/rfc/rfc8017', sourceTitle:'RFC 8017 RSA 规范' },
  { id:'dh', name:'Diffie–Hellman', kind:'密钥协商教学', hint:'素数 p 为 5–997，2 ≤ g ≤ p−2，1 ≤ a,b ≤ p−2。', principle:'双方各自保留指数 a、b，公开交换 gᵃ mod p 与 gᵇ mod p，再计算同一个 gᵃᵇ mod p。流程中展示公共值和各自私有运算。', flow:['公共参数与私有指数','只交换 A 和 B','双方各自做模幂','得到相同共享值'], warning:'小整数演示未验证安全子群、未提供身份认证和 KDF，不能防止中间人攻击；不是完整安全协议。', source:'https://www.rfc-editor.org/rfc/rfc2631', sourceTitle:'RFC 2631 DH 方法' },
  { id:'caesar', name:'凯撒密码', kind:'古典密码', hint:'只移动 A–Z / a–z，其他字符保持原样；偏移 0–25。', principle:'把英文字母映射为 0–25，加上固定偏移并对 26 取模。解密反向减偏移。可以直接看到每个字符的映射。', flow:['输入字符','字母编号与移位','模 26 得到输出'], warning:'仅 26 个偏移，可轻易穷举，不适合真实安全用途。' },
  { id:'vigenere', name:'维吉尼亚密码', kind:'古典多表密码', hint:'密钥使用 1–32 个英文字母；非英文字母不推进密钥。', principle:'循环使用密钥字母决定每个字母的偏移量。比固定移位复杂，但重复模式会泄露统计特征。', flow:['输入字符','循环密钥提供偏移','模 26 得到输出'], warning:'重复密钥的古典密码只适合教学，不适合现代安全场景。' },
  { id:'xor', name:'重复密钥 XOR', kind:'位运算基础', hint:'文字编码为 UTF-8 字节，密钥 1–32 字节；密文显示为 HEX。', principle:'两位相同输出 0，不同输出 1。每个明文字节与循环密钥字节异或。再次异或相同密钥能还原；这不等于安全的一次一密。', flow:['输入 UTF-8 字节','逐位异或循环密钥','输出密文字节'], warning:'重复短密钥会泄露结构，不是安全的一次一密。' },
]
