import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { createGuideLoader, BOOK_COMMIT } from './loader.js'
const manifest = JSON.parse(readFileSync(new URL('../../../public/life-guide/manifest.json', import.meta.url)))
const chapter = JSON.parse(readFileSync(new URL('../../../public/life-guide/chapter-01.json', import.meta.url)))
const response = data => new Response(JSON.stringify(data), { headers: { 'content-type': 'application/json' } })
test('manifest and successful chapters are memory-cached across route visits', async () => { let requests = 0; const loader = createGuideLoader(async url => { requests++; return response(url.includes('manifest') ? manifest : chapter) }); assert.equal((await loader.manifest()).commit, BOOK_COMMIT); await loader.manifest(); const first = await loader.chapter(manifest.chapters[0]); assert.equal(await loader.chapter(manifest.chapters[0]), first); assert.equal(requests, 2) })
test('failed requests remain retryable, not cached', async () => { let calls = 0; const loader = createGuideLoader(async () => ++calls === 1 ? new Response('error', { status: 503 }) : response(chapter)); await assert.rejects(loader.chapter(manifest.chapters[0])); assert.equal((await loader.chapter(manifest.chapters[0])).number, 1); assert.equal(calls, 2) })
test('pinned manifest rejects altered revision, count or chapter path', async () => { for (const data of [{ ...manifest, commit: 'other' }, { ...manifest, count: 658 }, { ...manifest, chapters: [{ ...manifest.chapters[0], url: 'https://evil.example/x' }, ...manifest.chapters.slice(1)] }]) await assert.rejects(createGuideLoader(async () => response(data)).manifest()) })
test('malformed or incomplete chapters never enter cache', async () => { for (const data of [{ ...chapter, number: 2 }, { ...chapter, entries: [] }, { ...chapter, entries: chapter.entries.map((entry, i) => i === 0 ? { ...entry, id: '1-0' } : entry) }]) await assert.rejects(createGuideLoader(async () => response(data)).chapter(manifest.chapters[0])) })
test('HTML SPA fallback and unsafe paths are rejected', async () => { const loader = createGuideLoader(async () => new Response('<html>fallback</html>')); await assert.rejects(loader.manifest()); await assert.rejects(loader.chapter({ ...manifest.chapters[0], url: '/other' })) })
test('aborted callers cannot read cached data or cache late responses', async () => { let calls = 0; const controller = new AbortController(); const loader = createGuideLoader(async () => { calls++; controller.abort(); return response(chapter) }); await assert.rejects(loader.chapter(manifest.chapters[0], controller.signal), { name: 'AbortError' }); await loader.chapter(manifest.chapters[0]); assert.equal(calls, 2); await assert.rejects(loader.chapter(manifest.chapters[0], controller.signal), { name: 'AbortError' }) })
