import test from 'node:test'
import assert from 'node:assert/strict'
import { READER_KEY, readReader, writeReader, parseGuideQuery, guideQuery, validEntryId } from './reader.js'
function storage() { const data = new Map([['other-game-save', 'keep']]); return { data, getItem: key => data.get(key) ?? null, setItem: (key, value) => data.set(key, value), removeItem: key => data.delete(key) } }
test('new visitors read no automatic persisted record', () => { const s = storage(); assert.deepEqual(readReader(s), { enabled: false, saved: [], resume: '', warning: '' }); assert.equal(s.data.size, 1) })
test('opt-in stores only bounded entry IDs, not query, account or book text', () => { const s = storage(); assert.equal(writeReader(s, { enabled: true, saved: ['1-1', '1-1', '34-2', '../x'], resume: '2-4', query: 'private', account: 'private' }), ''); assert.deepEqual(JSON.parse(s.getItem(READER_KEY)), { version: 1, enabled: true, saved: ['1-1', '34-2'], resume: '2-4' }); assert.equal(readReader(s).resume, '2-4') })
test('clearing reader leaves unrelated storage untouched', () => { const s = storage(); writeReader(s, { enabled: true, saved: [], resume: '' }); writeReader(s, { enabled: false }); assert.equal(s.getItem(READER_KEY), null); assert.equal(s.getItem('other-game-save'), 'keep') })
test('corrupt, huge and wrong-version records degrade to session mode without overwriting', () => { for (const raw of ['{', 'x'.repeat(65537), '{"version":2}', '{"version":1,"enabled":false,"saved":[]}']) { const s = storage(); s.setItem(READER_KEY, raw); const result = readReader(s); assert.equal(result.enabled, false); assert.ok(result.warning); assert.equal(s.getItem(READER_KEY), raw) } })
test('blocked reads and quota errors do not crash reader', () => { const blocked = { getItem() { throw new Error('denied') }, setItem() { throw new Error('quota') }, removeItem() { throw new Error('denied') } }; assert.ok(readReader(blocked).warning); assert.ok(writeReader(blocked, { enabled: true, saved: [], resume: '' })); assert.ok(writeReader(blocked, { enabled: false })) })
test('entry identifiers reject paths, zero, padding, arrays and out-of-range chapters', () => { for (const id of ['1-1', '34-60']) assert.ok(validEntryId(id)); for (const id of ['0-1', '35-1', '01-1', '1-0', '1-200', ['1-1'], '1-1#x', null]) assert.equal(validEntryId(id), false) })
test('filter links round-trip every public control and page', () => { const state = { q: '借条 睡眠', chapter: '8', evidence: 'A', benefit: '自由', money: '少', value: '高', page: 2 }; assert.deepEqual(parseGuideQuery(guideQuery(state)), { ...state, entry: '' }); assert.deepEqual(guideQuery({ page: 1 }), {}) })
test('malformed query values normalize without serializing personal records', () => { const result = parseGuideQuery({ q: ['x'], chapter: '35', evidence: 'D', page: '-4', entry: '../x', money: 'many', value: '最高' }); assert.equal(result.q, ''); assert.equal(result.chapter, ''); assert.equal(result.page, 1); assert.equal(result.entry, ''); assert.deepEqual(guideQuery({ saved: ['1-1'], resume: '2-1', onlySaved: true, entry: '2-1' }), { entry: '2-1' }); assert.equal(parseGuideQuery({ q: 'a'.repeat(200) }).q.length, 100) })
