<template>
  <main class="content-page">
    <header class="arc-heading"><div><p class="section-kicker">SPACE ARCADE / FROST EMBER</p><h1>寒境火种</h1><p>风雪会来，火不能灭。围绕暖炉建一座聚落，让每个人都有食物、工作和温暖。</p></div><RouterLink class="arc-back" to="/games">← 游戏大厅</RouterLink></header>
    <div class="arc-bank"><div v-for="(name,id) in resourceNames" :key="id"><span>{{name}}</span><strong :data-winter-resource="id">{{Math.floor(hud.resources[id])}}</strong></div></div>
    <div class="arc-layout"><section>
      <div ref="stage" class="arc-stage winter-stage" :class="{'is-expanded':expanded}" tabindex="0" aria-label="寒境火种可交互聚落地图，方向键选择土地，回车建造" :data-phase="phase" :data-day="hud.day" :data-time="hud.elapsed.toFixed(2)" :data-buildings="hud.buildings.length" :data-furnace="hud.furnace" :data-health="hud.health.toFixed(1)" :data-comfort="hud.comfort.toFixed(1)" @pointermove="hover" @click="clickTile">
        <div ref="mount" class="arc-canvas" />
        <div class="arc-hud"><div><span>第 {{endless?hud.day:Math.min(hud.day,5)}} 天 · {{hud.storm?'风雪':'晴冷'}} {{Math.ceil(48-hud.clock)}}s</span><strong :aria-label="`室外 ${hud.outside} 度，体感 ${Math.round(hud.comfort)} 度`">{{hud.outside}}° → {{Math.round(hud.comfort)}}°</strong><span>外 → 内 · {{hud.powered?'供热':'停炉'}} · {{speed}}×</span></div><div><span>{{hud.residents}} 人 · 健康 / 士气</span><strong>{{Math.ceil(hud.health)}}% / {{Math.ceil(hud.morale)}}%</strong><meter :value="hud.health" min="0" max="100" aria-label="居民整体健康" /></div></div>
        <div class="arc-stage-actions"><button type="button" @click.stop="toggle">{{expanded?'收起聚落':'放大聚落'}}</button><button v-if="canAct" type="button" @click.stop="pause">暂停</button><button v-for="rate in [1,2,4]" :key="rate" type="button" :aria-pressed="speed===rate" @click.stop="speed=rate">{{rate}}×</button><RouterLink to="/games" @click.stop>大厅 ↗</RouterLink></div>
        <div v-if="phase!=='playing'||hud.choices.length||error" class="arc-overlay"><div><p class="section-kicker">{{hud.choices.length?'A NEW DAY':'FROST EMBER / ORIGINAL SOLO GAME'}}</p><h2>{{error?'画面暂时无法打开。':hud.choices.length?'黎明，选择一份补给。':phase==='paused'?'风雪也停下了。':phase==='won'?'冰原上的灯，还亮着。':phase==='lost'?'这次火种没能留下。':'先让暖炉升起来。'}}</h2><p>{{error||(hud.choices.length?'时间暂停。你的选择会影响接下来的寒潮。':phase==='ready'?'安排采集、建设设施、升级暖炉。坚持五天后救援抵达；也可以开启无尽寒冬。':phase==='paused'?'岗位、采集、远征和天气全部暂停。':hud.notes.at(-1))}}</p>
          <div v-if="hud.choices.length" class="arc-choices"><button v-for="item in hud.choices" :key="item.id" type="button" :data-winter-supply="item.id" @click.stop="supply(item.id)"><strong>{{item.name}}</strong><span>{{item.note}}</span></button></div>
          <template v-else-if="!error"><label v-if="phase!=='paused'">生存目标<select v-model="endless"><option :value="false">五天救援</option><option :value="true">无尽寒冬 · 随时结束本局</option></select></label><button type="button" class="button button-primary" @click.stop="phase==='paused'?resume():start()">{{phase==='paused'?'继续聚落':phase==='ready'?'点亮火种':'重建聚落'}}</button><p v-if="['won','lost','ended'].includes(phase)">生存 {{Math.floor(hud.elapsed)}} 秒 · {{hud.residents}} 位居民 · {{hud.buildings.length}} 座设施</p></template>
        </div></div>
      </div>
      <section class="arc-card arc-building-menu"><header><h2>聚落规划</h2><p class="arc-note">选建筑，再点击地块放置；也能用方向按钮或键盘选择格位、回车确认。绿色可建，红色不能建。点击已有建筑查看与升级。</p></header>
        <div class="arc-building-grid"><button v-for="item in WINTER_BUILDINGS" :key="item.id" type="button" :data-winter-building="item.id" :disabled="!canAct" :aria-pressed="selected===item.id" @click="selectBuilding(item.id)"><strong>{{item.name}}</strong><small>{{item.wood}} 木 · {{item.iron}} 铁</small><small>{{item.note}}</small></button></div>
        <p class="arc-map-label" :class="{'arc-invalid':selected&&!target.ok}">{{selected?target.reason:inspected?`${WINTER_BUILDINGS.find(b=>b.id===inspected.kind).name} · ${inspected.level} 级`:'选一块空地，开始规划。'}} · 地块 {{cursor.x+1}}, {{cursor.y+1}}</p>
        <div class="arc-position"><button v-for="(offset,name) in offsets" :key="name" type="button" :disabled="!canAct" :aria-label="`地块${name}`" @click="adjust(...offset)">{{name}}</button><button v-if="selected" type="button" class="button button-primary" :disabled="!canAct||!target.ok" @click="place">确认建造</button><button v-if="selected" type="button" class="arc-small" @click="selected='';paint()">取消蓝图</button><button v-if="inspected&&!selected" type="button" class="arc-small" :disabled="!canAct||inspected.level>=3" @click="act(()=>upgradeWinterBuilding(state,inspected.id))">{{inspected.level>=3?'已达 3 级':`升级 · ${upgradeCost}`}}</button></div>
        <p class="arc-note">床位 {{hud.residents}} / {{capacity}} · 暖炉供热圈内的住宅更舒适。住宅每级加 4 个床位；生产设施没有工人就不会自动产出。</p>
      </section>
      <section class="arc-card"><h2>把决定做在寒潮之前。</h2><p>每个游戏日 48 秒，后半段有暴风雪，气温逐日下降。体感低于 5°C 会影响整体健康与士气；煤耗尽会停炉，食物耗尽会伤害居民。体感是简化游戏指标，不是现实建筑热工模型。</p><p>先建锯木场、燃料站和厨房，再升级暖炉。需要铁时建矿井并调动矿工，需要治疗时建医务所和安排医护。远征会临时占用 2 位居民，归来后需要重新分工。Esc 暂停，方向键选地，Enter 建造。</p></section>
    </section><aside class="arc-sidebar">
      <section class="arc-card"><p class="section-kicker">KEEP THE FIRE</p><h2>暖炉 · Lv.{{hud.furnace}}</h2><p>下个寒潮：约 {{-18-Math.min(9,hud.day)*6-14}}°C。提高热量会增加耗煤，不能只开强火不采煤。</p><div class="arc-position"><button v-for="(name,index) in ['停炉','标准','强火']" :key="name" type="button" class="arc-small" :aria-pressed="hud.heatMode===index" :disabled="!canAct" @click="act(()=>setWinterHeat(state,index))">{{name}}</button></div><button type="button" class="arc-small" :disabled="!canAct||hud.furnace>=4" @click="act(()=>upgradeFurnace(state))">{{hud.furnace>=4?'已达 4 级':`升级 · ${18+hud.furnace*10} 木 · ${4+hud.furnace*4} 铁`}}</button><p class="arc-note" role="status">{{hud.notes.at(-1)}}</p></section>
      <section class="arc-card"><h2>每个人的位置</h2><p>空闲 {{idle}} 人{{hud.expedition?' · 远征 2 人':''}}。岗位调整立即生效。</p><div v-for="job in WINTER_JOBS" :key="job.id" class="arc-job"><span>{{job.name}}</span><div><button type="button" :aria-label="`减少${job.name}岗位`" :disabled="!canAct||!hud.jobs[job.id]" @click="act(()=>assignWinter(state,job.id,-1))">−</button><strong :data-job="job.id">{{hud.jobs[job.id]}}</strong><button type="button" :aria-label="`增加${job.name}岗位`" :disabled="!canAct||!idle||jobUnavailable(job.id)" @click="act(()=>assignWinter(state,job.id,1))">＋</button></div></div><label>口粮配给<select :value="hud.ration" :disabled="!canAct" @change="act(()=>setWinterRation(state,$event.target.value))"><option value="scarce">节约 · 食耗低，士气下降</option><option value="normal">标准</option><option value="generous">丰盛 · 食耗高，士气提升</option></select></label></section>
      <section class="arc-card"><h3>紧急采集</h3><p class="arc-note">每 3 个游戏秒可领取一次 +4 补给，不替代岗位生产。</p><div class="arc-position"><button v-for="(name,id) in {wood:'木材',coal:'煤',food:'食物'}" :key="id" type="button" :disabled="!canAct||hud.gatherCooldown>0" @click="act(()=>gatherWinter(state,id))">{{name}} +4</button></div><h3>研究工坊</h3><div class="arc-research"><button v-for="item in WINTER_RESEARCH" :key="item.id" type="button" class="arc-small" :disabled="!canAct||!has('workshop')||hud.research.includes(item.id)||hud.resources.wood<item.wood||hud.resources.iron<item.iron" @click="act(()=>researchWinter(state,item.id))">{{hud.research.includes(item.id)?'✓ ':''}}{{item.name}} · {{item.wood}} 木 / {{item.iron}} 铁<br>{{item.note}}</button></div></section>
      <section class="arc-card"><h3>雪原远征</h3><template v-if="hud.expedition"><p>{{destinationNames[hud.expedition.destination]}} · 约 {{Math.ceil(hud.expedition.remaining)}}s 后归来</p><progress class="arc-progress" :value="20-hud.expedition.remaining" max="20" aria-label="远征进度" /></template><div v-else class="arc-research"><button v-for="(name,id) in destinationNames" :key="id" type="button" class="arc-small" :disabled="!canAct||!has('outpost')||hud.residents<4" @click="act(()=>sendWinterExpedition(state,id))">{{name}} · 2 人 / 20s</button></div><p class="arc-note">需要远征哨站。救援居民受床位上限限制；燃料、铁和木材会真实计入库存。</p><ol class="arc-log"><li v-for="(note,i) in hud.notes" :key="i">{{note}}</li></ol><button v-if="phase==='playing'||phase==='paused'" type="button" class="arc-small" @click="finish">结束本局</button></section>
      <p class="arc-note">原创单机冬日建造游戏，不是《无尽冬日》的官方版本，也没有使用其代码、商标美术或游戏资产。免费、无充值、无联盟联网、不保存或上传进度。离开窗口自动暂停。</p>
    </aside></div>
  </main>
</template>
<script setup>
import { computed, onMounted, onUnmounted, ref, shallowRef } from 'vue'
import { RouterLink } from 'vue-router'
import { WINTER_BUILDINGS, WINTER_JOBS, WINTER_RESEARCH, createWinter, stepWinter, winterCapacity, winterIdle, winterPlacement, buildWinter, upgradeWinterBuilding, upgradeFurnace, assignWinter, researchWinter, gatherWinter, setWinterHeat, setWinterRation, sendWinterExpedition, chooseWinterSupply } from '../features/arcade/winter.js'
import { createArcadeCanvas, paintWinter, pickWinterTile } from '../features/arcade/canvas.js'
import { useArcadeLoop } from '../features/arcade/useLoop.js'
import { useExpandedScene } from '../utils/useExpandedScene.js'
import '../features/arcade/arcade.css'
const stage=ref(null),mount=ref(null),phase=ref('ready'),error=ref(''),endless=ref(false),speed=ref(1),selected=ref(''),cursor=ref({x:3,y:4})
const resourceNames={wood:'木材',coal:'煤',food:'食物',iron:'铁'}, destinationNames={fuel:'燃料储备点',ruins:'废弃工厂',survivors:'幸存者信号'}, offsets={向左:[-1,0],向上:[0,-1],向下:[0,1],向右:[1,0]}
let state=createWinter(),scene,motion;const hud=shallowRef(structuredClone(state)),{expanded,toggle}=useExpandedScene(pause)
const canAct=computed(()=>phase.value==='playing'&&!hud.value.choices.length),capacity=computed(()=>winterCapacity(hud.value)),idle=computed(()=>winterIdle(hud.value)),target=computed(()=>winterPlacement(hud.value,selected.value,cursor.value.x,cursor.value.y)),inspected=computed(()=>hud.value.buildings.find(b=>b.x===cursor.value.x&&b.y===cursor.value.y)),upgradeCost=computed(()=>{const b=inspected.value,def=WINTER_BUILDINGS.find(i=>i.id===b?.kind);return def?`${def.wood*b.level} 木 / ${def.iron*b.level} 铁`:''})
function publish(){hud.value=structuredClone(state)}
function paint(){scene?.render(state,{...cursor.value,ok:target.value.ok},selected.value,motion?.matches)}
const loop=useArcadeLoop(dt=>{for(let i=0;i<speed.value;i++){stepWinter(state,dt);if(state.status!=='playing'||state.choices.length)break}if(state.status!=='playing'){phase.value=state.status;return false}return !state.choices.length},publish,paint)
function focus(){stage.value?.focus({preventScroll:true})}
function pause(){if(phase.value!=='playing')return;loop.stop();phase.value='paused';publish();paint()}
function resume(){if(!scene||error.value||document.hidden)return;phase.value='playing';focus();if(!state.choices.length)loop.start()}
function start(){state=createWinter(endless.value);selected.value='';cursor.value={x:3,y:4};publish();paint();resume()}
function supply(id){if(chooseWinterSupply(state,id)){publish();paint();resume()}}
function finish(){loop.stop();state.choices=[];state.status='ended';phase.value='ended';publish();paint()}
function act(fn){if(!canAct.value)return;fn();publish();paint()}
function has(kind){return hud.value.buildings.some(b=>b.kind===kind)}
function jobUnavailable(id){return id==='iron'&&!has('mine')||id==='medic'&&!has('clinic')}
function selectBuilding(id){if(!canAct.value)return;selected.value=id;const tiles=[];for(let x=0;x<7;x++)for(let y=0;y<7;y++)tiles.push({x,y});cursor.value=tiles.sort((a,b)=>Math.hypot(a.x-3,a.y-3)-Math.hypot(b.x-3,b.y-3)).find(at=>winterPlacement(state,id,at.x,at.y).ok)||{x:3,y:4};paint()}
function adjust(x,y){cursor.value={x:Math.max(0,Math.min(6,cursor.value.x+x)),y:Math.max(0,Math.min(6,cursor.value.y+y))};paint()}
function place(){if(!selected.value)return;act(()=>buildWinter(state,selected.value,cursor.value.x,cursor.value.y));focus()}
function hover(event){if(!scene||event.target.closest('button,a,select,.arc-overlay')||event.pointerType==='touch')return;const at=pickWinterTile(scene.position(event));if(at.x>=0&&at.x<7&&at.y>=0&&at.y<7){cursor.value=at;paint()}}
function clickTile(event){if(event.target.closest('button,a,select,.arc-overlay')||!scene)return;const at=pickWinterTile(scene.position(event));if(at.x<0||at.x>6||at.y<0||at.y>6)return;cursor.value=at;focus();if(selected.value)place();else paint()}
function keydown(event){if(document.activeElement!==stage.value||event.ctrlKey||event.metaKey||event.altKey)return;const k=event.key.toLowerCase();if(!['arrowleft','arrowright','arrowup','arrowdown','enter','escape'].includes(k))return;event.preventDefault();if(k==='escape'&&!event.repeat){phase.value==='paused'?resume():pause();return}if(!canAct.value)return;if(k==='enter'&&!event.repeat)place();else if(k.startsWith('arrow'))adjust(k==='arrowleft'?-1:k==='arrowright'?1:0,k==='arrowup'?-1:k==='arrowdown'?1:0)}
function visibility(){if(document.hidden)pause()}
function motionChange(){paint()}
onMounted(()=>{motion=matchMedia('(prefers-reduced-motion: reduce)');motion.addEventListener('change',motionChange);try{scene=createArcadeCanvas(mount.value,paintWinter);paint()}catch(e){error.value=e.message}window.addEventListener('keydown',keydown);window.addEventListener('blur',pause);document.addEventListener('visibilitychange',visibility)})
onUnmounted(()=>{loop.stop();scene?.dispose();motion?.removeEventListener('change',motionChange);window.removeEventListener('keydown',keydown);window.removeEventListener('blur',pause);document.removeEventListener('visibilitychange',visibility)})
</script>
